### ISSUE TITLE
Angular SPA B2C and protected Web API Tutorial

### ISSUE THREAD

**Issue by vertonghenb** [Azure-Samples/ms-identity-javascript-angular-spa-aspnet-webapi-multitenant#8]
## Library
- [x] `@azure/msal-angular@1.x.x`

## Description
Is there an available tutorial for an Angular single-page application that authenticates users with Azure AD **B2C** and calls a protected ASP.NET Core Web API. (Notice the B2C) ?

**Comment by derisen** [comment]
@vertonghenb not quite, but there's an [angular B2C app](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa) calling a [Node.js web api](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi), and there's also a [.NET Core B2C protected web api](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C).

**Comment by derisen** [comment]
Closing, let us know if you need further guidance.
